### ISSUE TITLE
Implement "BMP Raw" message type

### ISSUE THREAD

**Issue by ryeleo** [routeviews/gobmp#2]
GoBMP does not discuss support for BMP Raw messages.

> BMP RAW feed is a binary RAW BMP feed from the router. No filtering or alteration is performed
> Each Kafka message is a complete BMP message, including all BGP data that goes along with that message

*For more info, see [BMP RAW Messages](https://www.openbmp.org/api/kafka_message_schema.html#2-bmp-raw-messages)*

**Comment by ryeleo** [comment]
I believe BMP Raw is the bread & butter for Route Views data, so I think this is definitely blocking us from using goBMP over OpenBMP today.

However, I haven't touched Route Views BMP solution in some time, so I'm confirming this with Alistair.

**Comment by tobez** [comment]
This has been implemented in the `2-implement-bmp-raw-message-type` branch and merged into `master` in this fork.
