### ISSUE TITLE
Enable adding peers without restarting GoBMP process

### ISSUE THREAD

**Issue by ryeleo** [routeviews/gobmp#3]
Route Views needs to be able to add peers very often. 
If we have to restart the BMP stack anytime we add a peer, then the produced 'BMP data stream' would often have little 'outages' -- that would be a bummer for people who are continuously pulling data from the Kafka stream.

**Comment by tobez** [comment]
This has been implemented in the `4-mimic-openbmps-topics-and-group-auto-mapping` branch and merged into `master` in this fork.
