### ISSUE TITLE
Mimic OpenBMP's Topics and Group auto-mapping

### ISSUE THREAD

**Issue by ryeleo** [routeviews/gobmp#4]
RV heavily leverage openBMP’s topics and group mapping. See the [`group` and `topics` objects in OpenBMPs example config](https://github.com/SNAS/openbmp/blob/master/Server/openbmpd.conf). 

Route Views leverages OpenBMP today, which enables us to produce a consistent topic format. 

We haven’t dug through the gobmp code enough to understand how topics are being formatted. Are topic formats hard-coded?

**Comment by tobez** [comment]
This has been implemented in the `4-mimic-openbmps-topics-and-group-auto-mapping` branch and merged into `master` in the routeviews fork.
